---
title: "Research Proposal"
author: "Nicholas Potter"
date: "`r lubridate::date(Sys.time())`"
link-citations: true
pandocExtensions: tex_math_dollars
bibliography: ../library.bib
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Nature of the Problem

# Research Question

* **Research Topic**: (general subject)
* **Research Question**: (complete sentence)
* **Research Hypothesis**: (complete sentence)

# Survey of Literature

# Research Design

# References

* Does the proposal explain the problem or issue sufficiently to make it interesting and worthy of a reader's time? Why or why not? Is there anything in the introductory section of the proposal that ought to be explained in more detail?
* Do you understand the research question? In other words, can you explain what the research will attempt to do or prove? Is there a clear statement of this? Ifso, identify it. If not, say so.
* Does the author appear to have identified the major studies previously done on the topic? Has he or she identified those studies' contributions and shortcomings? (The proposed research should build on the contributions and/or correct one or more of the shortcomings.)
* Do you understand clearly and exactly what the author intends to do to complete this research? Are there any details missing from the description? If so, what are they? Has the author identified a reasonable data set with which to test his or her hypothesis? Has he or she adequately explained his or her testing methodology?
* Are there enough sources to write a convincing paper?
* In sum, what do you see as the proposal's strengths, and what do you see as its weaknesses?

Your commentary should conclude with an explicit statement about whether the proposal is acceptable as is or not. Ifit is not, you should provide specific guidelines for what needs to be done to make the proposal acceptable. Again, remember that your feedback should be supportive but honest.





