---
title: "Graduate Research Plan"
author: "Nicholas A Potter"
date: "August 4, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Present an original research topic that you would like to pursue in graduate school. Describe the research idea, your general approach, as well as any unique resources that may be needed for accomplishing the research goal (i.e., access to national facilities or collections, collaborations, overseas work, etc.) You may choose to include important literature citations. Address the potential of the research to advance knowledge and understanding within science as well as the potential for broader impacts on society. The research discussed must be in a field listed in the Solicitation (Section X, Fields of Study).

Important questions to ask yourself before writing the statement:

What issues in the scientific community are you most passionate about?
Do you possess the technical knowledge and skills necessary for conducting this work, or will you have sufficient mentoring and training to complete the study?
Is this plan feasible for the allotted time and institutional resources?
How will your research contribute to the "big picture" outside the academic context?
How can you draft a plan using the guidelines presented in the essay instructions?
How does your proposed research address the Intellectual Merit and Broader Impacts criteria?